feat: add `mods` into component panel
V4Fire/DevTools pull request #12
Opened 2024-03-04 09:50 UTC by ItMaga

closes #9

2024-03-04 10:11 UTC, shining-mind reviewed
Давай сразу сделаем вывод значений модификаторов селектом - по дефолту должно быть выбрано текущее значение. При смене модификатора - на странице у компонента он тоже должен обновиться.

2024-03-20 09:33 UTC, shining-mind requested changes

2024-03-20 09:33 UTC, shining-mind commented on packages/devtools-core/src/components/form/b-custom-select/b-custom-select.ss
> +			{{ value }}
Здесь бы надо кнопку сделать, чтобы при клике на значение открывался дропдаун. А так получается, что дропдаун будет открываться только по клику на стрелочку.

2024-03-20 09:33 UTC, shining-mind commented on packages/devtools-core/src/components/form/b-custom-select/b-custom-select.ss
> +- include '@super/components/form/b-select'|b as placeholder
Не нужно указывать super, если мы создаем новый компонент, а не переопределяем существующий.

```suggestion
- include 'components/form/b-select'|b as placeholder
```

2024-03-20 09:33 UTC, shining-mind commented on packages/devtools-core/src/components/form/b-custom-select/b-custom-select.ss
Может назовем компонент просто `b-dropdown`?

2024-03-20 09:33 UTC, shining-mind commented on packages/devtools-core/src/components/form/b-custom-select/b-custom-select.ts
> +	override activeStore!: iActiveItems['activeStore'];
А зачем переопределять activeStore? Можно вывести выбранное значение через поле `text`.

2024-03-20 09:33 UTC, shining-mind commented on packages/devtools-core/src/components/form/b-custom-select/b-custom-select.ss
> +			{{ value }}
Ещё надо проверить, что корректно работает обработчик keydown, что можно с помощью стрелочек открыть/закрыть дропдаун и выбрать значение.

2024-03-20 09:33 UTC, shining-mind commented on packages/devtools-core/src/features/components/b-components-panel/b-components-panel.styl
> +		flex-grow 1
Если я верно понимаю, это нужно, чтобы контейнер становился больше, когда открывается дропдаун?

2024-03-20 09:33 UTC, shining-mind commented on packages/devtools-core/src/features/components/b-components-panel/interface.ts
> +	select?: {
Название нужно какое-то другое, например `allowedValues`/`availableOptions` или как-то похоже

2024-03-20 09:33 UTC, shining-mind commented on packages/devtools-core/src/features/components/b-components-panel/interface.ts
> +		onActionChange(ctx: bSelect, value: unknown): void;
не очень понятно, а зачем тут хэндлер

2024-03-20 09:33 UTC, shining-mind commented on packages/devtools-core/src/features/components/b-components-panel/modules/b-components-panel-item/b-components-panel-item.styl
> +	flex-row def
В девтулзах давай будем использовать стандартные свойства, т.е.: `display`, `flex-direction`

2024-03-20 09:33 UTC, shining-mind commented on packages/devtools-core/src/features/components/b-components-panel/modules/b-components-panel-item/b-components-panel-item.ts
> +	select?: Dictionary;
Вообще здесь же конкретный тип из интерфейса должен быть, а не произвольный словарь

2024-03-20 09:33 UTC, shining-mind commented on packages/devtools-core/src/features/components/b-components-panel/modules/helpers.ts
> +			const {value: valueByKey, select, warning} = getValue(ctx, data, key);
возможно `getValue` надо переименовать, так как он возвращает не только значение, но и дополнительную метаинформацию

2024-03-20 09:33 UTC, shining-mind commented on packages/devtools-extension/src/features/components/b-components-panel/b-components-panel.ts
> +function evalSetComponentMod(key: string, value: unknown, componentId: string, componentName: string) {
Может сделать глобальный тип:

```ts
// это примерное название
type ComponentQuery = Pick<ComponentInterface, 'componentId' | 'componentName'>;
```

и тогда можно будет везде заменить в функциях два аргумента на один:
```ts

function evalSetComponentMod(key: string, value: unknown, сtx: ComponentQuery) {
  // ... 
}

// ...

evalSetComponentMod(key, value,	Object.select(this.componentData, ['componentId', 'componentName']));
```

Или это более многословно, как думаешь?

2024-03-20 09:33 UTC, shining-mind commented on packages/devtools-extension/src/features/components/b-components-panel/b-components-panel.ts
> +	const {component} = <{component?: iBlock} & Element>node;
У нас есть тип `ComponentElement` имеет смысл его использовать он определен тут: https://github.com/V4Fire/Client/blob/72fe9367e0f2cbb24ab34463d86aae9b8ce34d53/src/core/component/interface/component/types.ts#L21

2024-03-20 15:35 UTC, ItMaga commented on packages/devtools-core/src/features/components/b-components-panel/b-components-panel.styl
> +		flex-grow 1
Тут была проблема, если открывать дропдаун в конце списка, то добавлялся скролл на высоту контента 

Вот скрин
![image](https://github.com/V4Fire/DevTools/assets/51162910/de7aa865-d9cd-4aa2-8a84-8882a300f19b)

2024-03-20 15:35 UTC, ItMaga commented on packages/devtools-core/src/features/components/b-components-panel/interface.ts
> +		onActionChange(ctx: bSelect, value: unknown): void;
Это обработчик выбора элемента в дропдауне, чтобы можно было задать любое действие селекту, в случае модификаторов - это изменение модификатора у ноды компонента

2024-03-20 15:36 UTC, ItMaga commented on packages/devtools-core/src/components/form/b-custom-select/b-custom-select.ts
> +	override activeStore!: iActiveItems['activeStore'];
А поле text не филд же, не обновляется шаблон если выводить через поле текст. При изменении через список обновляется `activeStore`, которая в свою очередь является зависимостью `value`. Или я что-то не так понял?

2024-03-20 15:36 UTC, ItMaga commented on packages/devtools-core/src/components/form/b-custom-select/b-custom-select.ss
Думал над вариантом `b-dropdown-select`, как будто `b-dropdown` не всегда подразумевает что есть функционал селекта, а просто выпадающий список.

Что думаешь над `b-dropdown-select`?

2024-03-20 15:37 UTC, ItMaga commented on packages/devtools-core/src/features/components/b-components-panel/interface.ts
> +	select?: {
Имеешь в виду переименовать select или select.items? Я тут подразумевал, что тут для селекта могут передаваться не только значения, но и какие-то доп параметры, например обработчик, пропсы, атрибуты и т.д.

2024-03-20 15:41 UTC, ItMaga commented on packages/devtools-extension/src/features/components/b-components-panel/b-components-panel.ts
> +function evalSetComponentMod(key: string, value: unknown, componentId: string, componentName: string) {
Думаю можно, чтобы показать связность и если что-то поменяется, чтобы тс подсказал. Насчёт названия `ComponentQuery` в целом кажется окей, в контексте того, что это данные для получения компонента. Думал ещё что-то типа `ComponentIdentifiers`, потому что пока они у нас используется как идентификаторы для получения ноды, но `ComponentQuery` как будто более устойчиво к изменениям

2024-03-20 15:41 UTC, shining-mind commented on packages/devtools-core/src/components/form/b-custom-select/b-custom-select.ss
Ну, имхо просто длинное название получается.

2024-03-20 15:43 UTC, shining-mind commented on packages/devtools-core/src/components/form/b-custom-select/b-custom-select.ts
> +	override activeStore!: iActiveItems['activeStore'];
Да, точно textStore - это system, но его проще сделать филдом, чем activeStore. `textStore` должен синхронизироваться с `activeStore`.

2024-03-20 15:45 UTC, shining-mind commented on packages/devtools-core/src/features/components/b-components-panel/interface.ts
> +	select?: {
Ну, непонятно с какого перепуга item должен знать что-то об UI где он выводится. 

`Item` - это чисто метаинформация, которая никак не связана с UI. Предполагается, что `Item` может знать о том, что у него есть допустимый набор значений, но он точно ничего не должен знать об обработчиках, которые нужные для UI девтулзов.

2024-03-20 15:45 UTC, shining-mind commented on packages/devtools-core/src/features/components/b-components-panel/interface.ts
> +		onActionChange(ctx: bSelect, value: unknown): void;
Некорректно хэндлеры задавать Item'у, выше написал почему.

2024-03-20 15:55 UTC, ItMaga commented on packages/devtools-core/src/components/form/b-custom-select/b-custom-select.ss
> +			{{ value }}
А тут есть обработчик на открытие при клике на блок wrapper в базовом b-select, то есть сейчас открывается при клике на весь контейнер, но единственное, это не кнопка. Стоит переопределить весь контейнер и сделать кнопкой?

2024-03-20 16:02 UTC, shining-mind commented on packages/devtools-core/src/components/form/b-custom-select/b-custom-select.ss
> +			{{ value }}
Если обработчик есть, то ничего делать не надо. Но согласно требованиям ARIA кликабельными должны быть только интерактивные элементы: кнопки, чекбоксы, ссылки и т.д.

2024-03-21 10:11 UTC, ItMaga commented on packages/devtools-core/src/components/form/b-custom-select/b-custom-select.ts
> +	override activeStore!: iActiveItems['activeStore'];
Если сделать `textStore` филдом, то тоже не обновляется `activeStore`, как я понял, должен быть элемент инпута, чтобы `textStore` синхронизировался с `activeStore`

2024-03-21 10:28 UTC, shining-mind commented on packages/devtools-core/src/components/form/b-custom-select/b-custom-select.ts
> +	override activeStore!: iActiveItems['activeStore'];
Ну, у нас же теперь выбор только по клику без ввода через инпут, так что это нормально

2024-04-02 09:09 UTC, shining-mind commented on packages/devtools-core/src/components/form/b-dropdown/b-dropdown.ts
> +import bSelect, { component, field } from '@v4fire/client/components/form/b-select/b-select';
```suggestion
import bSelect, { component, field } from 'components/form/b-select/b-select';
```

2024-04-02 09:09 UTC, shining-mind commented on packages/devtools-core/src/components/form/b-dropdown/b-dropdown.ts
> +export * from '@v4fire/client/components/form/b-select/b-select';
```suggestion
export * from 'components/form/b-select/b-select';
```

2024-04-02 09:09 UTC, shining-mind commented on packages/devtools-core/src/features/components/b-components-panel/b-components-panel.ts
> +	onChangeMod(_key: string, _value: unknown): void {
```suggestion
	onItemChangeMod(_key: string, _value: unknown): void {
```

2024-04-02 09:09 UTC, shining-mind commented on packages/devtools-core/src/features/components/b-components-panel/modules/helpers.ts
> +					return {label: declFormatted, value: declFormatted};
как-то особо нет смысла делать label равный value

2024-04-02 09:09 UTC, shining-mind commented on packages/devtools-core/src/features/components/b-components-panel/modules/helpers.ts
> +	getData(data: ComponentData, key: string): {value: unknown; items?: Item['availableOptions']; warning?: Item['warning']};
я думаю всё-таки он должен возвращать не items, а `allowedValues`.

2024-04-02 09:09 UTC, shining-mind commented on packages/devtools-extension/src/features/components/b-components-panel/b-components-panel.ts
> +import type { ComponentQuery } from 'features/components/b-components-panel/interface';
Кажется, что это базовый тип, который должен быть условно на уровне `src/core`. Вообще я в прошлый раз предлагал этот тип использовать и в backend, чтобы не пробрасывать отдельно аргументы в функции поиска ноды.

Потому этот тип стоит определить на уровне backend.

2024-04-02 09:09 UTC, shining-mind commented on packages/devtools-core/src/features/components/b-components-panel/interface.ts
> +	availableOptions?: ItemOption[];
Наверное логичнее всё же будет назвать `allowedValues` там должно быть множество доступных значений (Set). Label тут лишний, потому что он всегда будет равен value и более того `label` - относится уже к представлению разрешенного значения в интерфейсе, и его явно не должно быть на уровне самого item'а.

Это скриншот типа значения модификатора.
<img width="700" alt="image" src="https://github.com/V4Fire/DevTools/assets/46344555/6cf06893-a4bd-46a5-aa03-56270e58379f">

2024-04-26 12:14 UTC, shining-mind approved these changes

2024-04-27 10:37 UTC, merged